# Generated by Django 2.2 on 2019-04-19 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysocial', '0003_auto_20190304_2159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
